apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-proj
spec:
  selector:
    matchLabels:
      app: go-proj
  template:
    metadata:
      labels:
        app: go-proj
    spec:
      containers:
      - name: go-proj
        image: damngoodpenguin/go-proj_go-proj:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8068
---
apiVersion: v1
kind: Service
metadata:
  name: go-proj-service
spec:
  selector:
    app: go-proj
  type: LoadBalancer
  ports:
  - port: 8068
    targetPort: 8068
    nodePort: 30000

